USE DATABASE TAXI_DW;

CREATE SCHEMA IF NOT EXISTS RAW;

CREATE SCHEMA IF NOT EXISTS STAGING;

CREATE SCHEMA IF NOT EXISTS CORE;

CREATE SCHEMA IF NOT EXISTS MARTS;

CREATE SCHEMA IF NOT EXISTS INGESTION_CONFIG;

CREATE SCHEMA IF NOT EXISTS INGESTION_AUDIT;